### ISSUE TITLE
Problem with installing on Centos

### ISSUE THREAD

**Issue by wood-chris** [semagrow/semagrow#28]
When I run ``mvn clean package -P tomcat-bundle`` (and with ``-DskipTests``) on Centos, I get the error:

    [ERROR] Failed to execute goal com.github.eirslett:frontend-maven-plugin:1.0:gulp (gulp build) on project semagrow-webgui: Failed to run task: 'gulp.js ' failed. (error code 137) -> [Help 1]

It seems I shouldn't need to install npm / gulp (vanilla Ubuntu doesn't have these and it does work!)

    [centos@test2 semagrow]$ java -version
    openjdk version "1.8.0_191"
    OpenJDK Runtime Environment (build 1.8.0_191-b12)
    OpenJDK 64-Bit Server VM (build 25.191-b12, mixed mode)

    [centos@test2 semagrow]$ mvn --version
    Apache Maven 3.6.0 (97c98ec64a1fdfee7767ce5ffb20918da4f719f3; 2018-10-24T18:41:47Z)
    Maven home: /home/centos/apache-maven-3.6.0
    Java version: 1.8.0_191, vendor: Oracle Corporation, runtime: /usr/lib/jvm/java-1.8.0-openjdk- 
    1.8.0.191.b12-0.el7_5.x86_64/jre
    Default locale: en_GB, platform encoding: UTF-8
    OS name: "linux", version: "3.10.0-862.11.6.el7.x86_64", arch: "amd64", family: "unix"

**Comment by gmouchakis** [comment]
This could be related to https://github.com/semagrow/semagrow/commit/30108330b5b5d38dbe43be40a43f0231027bc4c7 which addressees https://github.com/semagrow/semagrow/issues/23. Please roll-back to `"gulp-sass": "^2.0.1"` in `webgui/src/frontend/package.json` and try again.

Which CentOS version are you using?

**Comment by wood-chris** [comment]
Hmm, I've tried changing that line to ``"gulp-sass": "^3.1.0" and I still get the same error! 

    [centos@test2 semagrow]$ rpm -q centos-release
    centos-release-7-5.1804.4.el7.centos.x86_64

**Comment by gmouchakis** [comment]
I tried the build on a `CentOS Linux release 7.4.1708` running `Apache Maven 3.6.0` and `javac 1.8.0_191` and it completed successfully.
