### ISSUE TITLE
Docker base image

### ISSUE THREAD

**Issue by gmouchakis** [semagrow/semagrow#47]
Semagrow docker uses `tomcat:8.5-jre8-alpine` as its base image. Alpine uses `musl` and we should test its performance in comparison with `glibc` based images such as `tomcat/8.5-jre8-slim` which is bigger (alpine 106MB, slim 223MB) but maybe outperforms Alpine. Performance is more important for semagrow than disk space used especially if the difference is in MBs.

**Comment by acharal** [comment]
Great idea! We could also stress-test both Docker images using [semagrow/kobe](https://github.com/semagrow/kobe)

**Comment by antru6** [comment]
I compared both images using the fedbench queries and I got similar query execution times.
