### ISSUE TITLE
Semagrow GET

### ISSUE THREAD

**Issue by Iranox** [semagrow/semagrow#7]
Is it possible to use GET instead of POST ?If it is possible, how should the configuration file look like?

**Comment by acharal** [comment]
Sure, SemaGrow is using OpenRDF Sesame/RDF4J under the hood to comply with the [SPARQL protocol](https://www.w3.org/TR/sparql11-protocol/).
As far as SemaGrow accepting requests goes, it will automatically detect if it is a GET or POST request, so there is no need to declare anything special in the configuration.
