### ISSUE TITLE
docker image

### ISSUE THREAD

**Issue by PaulZH** [semagrow/semagrow#8]
I get a lot of warnings and errors during startup, see 
[semagrow.log.txt](https://github.com/semagrow/semagrow/files/701226/semagrow.log.txt).
At the end the server indicates 'started' but http wise I'm not able to connect.

From host: http://localhost:32775/
From within container: docker exec semagrow curl http://localhost:8080

No response in both cases. 

What am I missing?

**Comment by gmouchakis** [comment]
These errors are related to a feature that is not implemented in the container but Semagrow should work fine without it.

Semagrow's web interface is accessible at http://localhost:8080/SemaGrow not on http://localhost:8080. The SPARQL endpoint is accessible at http://localhost:8080/SemaGrow/sparql

**Comment by PaulZH** [comment]
Thanks,

Over here it runs at http://localhost:32783/SemaGrow/
